name: Release

on:
  push:
    branches:
      - deploy-actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:12
    steps:
      - uses: actions/checkout@v2
      - name: Checkout themes
        uses: actions/checkout@v2.0.0
        with:
          path: themes/novela
          ref: 'master'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.76.5'
      - name: Build
        run: hugo --minify
      - name: Setup GCP CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: hugo deploy
